language: node_js
node_js: '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
git:
  depth: 100
deploy:
  provider: heroku
  api_key:
    secure: YXkqKfdiyv9meh9EG5AQY9dX85B14vZVVnWnuTGo8pd46Cr+9P8l1G9Td1GoRsmAZ0g5x+CEteqzeCSUfmL7I8xJjx6i8KXRNTNgXY9Sl7+hdLDluxvmzniJX+9+LNpyGXQfRLwA63Pv751dRAkXkhobl0zb6a0yGh+dHHtGMpyElKrL1vSHOHp5kwBG95P9uHwicGoTgPeat7sfE42btE52Le1WeiytLl+2WYKtWICyaPw3apQBjPeiUN86LapRU/ZbXkQNBecwIqqjfGZmkaFhLty/WkdEuCv+iHUuklywP3KgwHSMgVEhYrecKfJ0foZLsKb+Z12Z7m1iKAw5xi/Kzg9+r8QAJq5ylqET+Gng4N5Xs9Wmu4L/5/z/Rx2OTwnZUlGpMsgvqtqpw2m3mUpkvSUzBPEQQHal9XeZBvzbWDUGLt3dr6mNiAhIdLTLUXsy6Ub6txdv3TBMu4oKD6JcVPVCpOVYcVUevEF9ZpXl7FhyAtX/uSuG5kLLbF//iJ2GgDFHI2MHcMFWEGrLYurwVYfx8OE5xMfIREIFwvL6NFjBYRRixqhGIY5WHGYgQjU4+Dvs2jn0JDy016RmjJEE00HTh1mNoE5QuNgxc4DLDWmm609OoA+Eiq3bLknLNekwjAEeTLbdJy2YhzBHQrP2k084tkBLGx6hmxwkx8c=
  app: eat-da-burger-das
